import React from "react";
import {
  Home,
  Code,
  Coffee,
  Building,
  Pizza,
  UtensilsCrossed,
  ChefHat,
  Wine,
  Beer,
  Grape,
  Salad,
  CookingPot,
  Croissant,
  IceCreamCone,
  Cake,
  Sandwich,
  Soup,
  Wallet,
  Coins,
  PiggyBank,
  CreditCard,
  Banknote,
  TrendingUp,
  Calculator,
  Receipt,
  Leaf,
  TreePine,
  Sprout,
  Flower,
  TreeDeciduous,
  Flower2,
  LeafyGreen,
  Trees,
  FlaskConical,
  TestTube,
  Beaker,
  Car,
  Briefcase,
} from "lucide-react";

export type IconComponent = React.ComponentType<{ className?: string }>;

export const contextIconMap: Record<string, IconComponent> = {
  Home,
  Code,
  Coffee,
  Building,
  Pizza,
  UtensilsCrossed,
  ChefHat,
  Wine,
  Beer,
  Grape,
  Salad,
  CookingPot,
  Croissant,
  IceCreamCone,
  Cake,
  Sandwich,
  Soup,
  Wallet,
  Coins,
  PiggyBank,
  CreditCard,
  Banknote,
  TrendingUp,
  Calculator,
  Receipt,
  Leaf,
  TreePine,
  Sprout,
  Flower,
  TreeDeciduous,
  Flower2,
  LeafyGreen,
  Trees,
  FlaskConical,
  TestTube,
  Beaker,
  // Legacy/extra icons that might exist in stored contexts
  Car,
  Briefcase,
};

export function getContextIconComponent(name: string): IconComponent {
  return contextIconMap[name] || Home;
}

export const contextIconOptions: ReadonlyArray<{
  value: string;
  icon: IconComponent;
  label: string;
}> = [
  { value: "Home", icon: Home, label: "Home" },
  { value: "Code", icon: Code, label: "Coding" },
  { value: "Coffee", icon: Coffee, label: "Kitchen" },
  { value: "Building", icon: Building, label: "Work" },
  // Food & Beverage Icons
  { value: "Pizza", icon: Pizza, label: "Food" },
  { value: "UtensilsCrossed", icon: UtensilsCrossed, label: "Dining" },
  { value: "ChefHat", icon: ChefHat, label: "Cooking" },
  { value: "Wine", icon: Wine, label: "Wine" },
  { value: "Beer", icon: Beer, label: "Beer" },
  { value: "Grape", icon: Grape, label: "Fermentation" },
  { value: "Salad", icon: Salad, label: "Healthy Food" },
  { value: "CookingPot", icon: CookingPot, label: "Meal Prep" },
  { value: "Croissant", icon: Croissant, label: "Bakery" },
  { value: "IceCreamCone", icon: IceCreamCone, label: "Desserts" },
  { value: "Cake", icon: Cake, label: "Baking" },
  { value: "Sandwich", icon: Sandwich, label: "Quick Meals" },
  { value: "Soup", icon: Soup, label: "Comfort Food" },
  // Finance Icons
  { value: "Wallet", icon: Wallet, label: "Personal Finance" },
  { value: "Coins", icon: Coins, label: "Savings" },
  { value: "PiggyBank", icon: PiggyBank, label: "Budget" },
  { value: "CreditCard", icon: CreditCard, label: "Credit" },
  { value: "Banknote", icon: Banknote, label: "Cash" },
  { value: "TrendingUp", icon: TrendingUp, label: "Investments" },
  { value: "Calculator", icon: Calculator, label: "Accounting" },
  { value: "Receipt", icon: Receipt, label: "Expenses" },
  // Plant/Nature Icons
  { value: "Leaf", icon: Leaf, label: "Plants" },
  { value: "TreePine", icon: TreePine, label: "Garden" },
  { value: "Sprout", icon: Sprout, label: "Growing" },
  { value: "Flower", icon: Flower, label: "Flowers" },
  { value: "TreeDeciduous", icon: TreeDeciduous, label: "Trees" },
  { value: "Flower2", icon: Flower2, label: "Gardening" },
  { value: "LeafyGreen", icon: LeafyGreen, label: "Herbs" },
  { value: "Trees", icon: Trees, label: "Forest" },
  // Science/Fermentation Icons
  { value: "FlaskConical", icon: FlaskConical, label: "Brewing" },
  { value: "TestTube", icon: TestTube, label: "Experiments" },
  { value: "Beaker", icon: Beaker, label: "Laboratory" },
];